#################
### AUTOSTART ###
#################
exec-once = quickshell -p $HOME/.config/quickshell/Bar.qml
exec-once = otd-daemon
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = $HOME/.config/hypr/scripts/wallpapers.sh
